name: Simple Build and Deploy VitePress Site

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}-build
  cancel-in-progress: true

on:
  push:
    branches: 
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/deploy.yml'
      - 'package.json'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List files in docs directory (디버깅)
        run: |
          echo "=== Listing docs directory ==="
          ls -la docs/
          echo "=== Listing docs/guide directory ==="
          ls -la docs/guide/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # Strapi 단계 일시적으로 제외
      # - name: Fetch Strapi Content and Generate Markdown
      #   run: npm run docs:fetch-content
      #   env:
      #     STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
      #     STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}

      - name: Build VitePress Site
        run: npm run docs:build

      - name: List build output (디버깅)
        run: |
          echo "=== Listing build output ==="
          ls -la docs/.vitepress/dist/
          echo "=== Listing guide directory in build output ==="
          ls -la docs/.vitepress/dist/guide/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 