# Simple workflow for deploying static content to GitHub Pages
name: GitHub Pages Setup

# 중복 실행 방지를 위한 concurrency 설정
concurrency:
  group: pages-setup-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # 이 워크플로우는 수동으로만 실행하거나, 
  # deploy.yml 파일이 수정될 때만 실행되도록 제한
  workflow_dispatch: # 수동 실행 허용
  push:
    branches:
      - main
    paths:
      - '.github/workflows/static.yml' # 이 파일 자체가 변경될 때만 실행
      # 필요하다면 다른 Pages 설정 관련 파일들 추가

# 권한 설정 (GitHub Pages에 필요한 최소 권한)
permissions:
  contents: read
  pages: write
  id-token: write

# 환경 설정
env:
  # Pages 설정과 관련된 환경 변수
  PAGES_ENV: production

jobs:
  # GitHub Pages 기본 설정 작업
  setup-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # 실제 빌드 및 배포는 deploy.yml에서 처리하도록 함
      - name: Notice
        run: |
          echo "GitHub Pages 기본 설정이 완료되었습니다."
          echo "실제 사이트 빌드 및 배포는 deploy.yml 워크플로우에서 처리됩니다."
